language: node_js
notifications:
  email: false
node_js:
  - '12'
  - '11'
  - '10'
  - '8'
script:
  - npm run test:prod && npm run build
before_install:
- npm install -g typescript
after_success:
  - npm run travis-deploy-once "npm run report-coverage"
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run deploy-docs"; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
